# Generated by Django 4.2 on 2023-05-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciepts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribes',
        ),
    ]
